# layer.conf for meta-diag-apps

# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

LAYERSERIES_COMPAT_diag_apps = "scarthgap"
BB_DANGLINGAPPENDS_WARNONLY = "1"

BBFILE_COLLECTIONS += "meta-diag-apps"
BBFILE_PATTERN_meta-diag-apps = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-diag-apps = "6"

LAYERVERSION_meta-diag-apps = "1"
LAYERSERIES_COMPAT_meta-diag-apps = "scarthgap"

# Layer dependencies
LAYERDEPENDS_meta-diag-apps = "core openembedded-layer"
# Additional dependencies for Go and networking recipes
